api-key=
api-secret=
recv-window=60000
type=SPOT
isolated=FALSE

rest-uri=https://testnet.binance.vision/api/v3/
rest-uri-margin=https://api.binance.com/sapi/v1/margin/

name=BNC-1
symbol= btcusdt
quantity = 0.002
interval = 5m

